### ISSUE TITLE
SSDP not discovered

### ISSUE THREAD

**Issue by Reginiano** [Yortw/RSSDP#21] opened 2016-06-28 14:53 UTC
Hello,
I'm publishing my application using RSSDP in windows 7.
When i try to discover the app by the RSSDP discovery- it works only if the discovery code is within the same published application. :/

I use IPV4, I have no firewall and I tried to disable/enable the SSDP/UPNP service, but it didn't help.
My goal is to find the published app by any of the Upnp scanners in the lan (right now it does not work).

I'd really appreciate your help,
Eyal.

**Comment by Yortw** [comment] 2016-06-28 21:55
Hmm, sorry, I am not sure what to suggest. You've checked all the usual suspects (firewall etc). It also seems very odd that it works only within the same app - I would expect it to at least work with different apps on the same PC - there is no in-process communication between the publisher and locator, so being in the same app should make no difference.

What kind of app are you publishing from? A window service? A UWP app? Console app? What framework?

If you download the Intel upnp tools does device sniffer find the service (or can you at least see packets being sent)?

If you run the RSSDP locator, can it find any other devices on your network (i.e not yours, but anything at all)?

Perhaps you could post your code for the publisher and locator setup/use?

**Comment by Reginiano** [comment] 2016-06-29 12:50
Yortw, thank you for your response. :+1: 

I'm publishing in a windows service with .Net framework 4.5.
Seems like the multicast is successful, but different from the other "normal" upnp.

**Device sniffer**: finds the RSSDP packets from a remote computer, but does not find other "normal" upnp in the network.
**Upnp Scanner** ([url](http://alax.info/blog/257)) or **Upnp Tester** [url](http://download.cnet.com/Universal-Plug-and-Play-Tester/3000-2085_4-10504740.html): Does not find RSSDP packets, finds all other "normal" upnp.

Why is that?

**Comment by Yortw** [comment] 2016-06-29 21:06
I don't know what's going on, the symptoms don't make sense. 

Since it's a service not a UWP/WinRT app then we can eliminate manifest permissions etc.

The RSSDP locator and publisher are designed to work together so even if they deviate from the SSDP spec (and I don't believe they do) they should find each other. The fact that Device Sniffer sees the packets indicates they're being sent/receivable on the remote machine so at the very least RSSDP should find itself without 'being in the same app'.

The packets *should* be consistent with the SSDP spec ("normal"), but at this point you're the only one who can tell as you have both sets of packets in the sniffer - I can't see what you're seeing.

**Does the Intel "Device Spy" app that comes in the same package as "Device Sniffer" show your device?**

I know that Device Spy won't show a device if either it can't parse the packet, or if the service end point that returns the device description document is invalid/unreachable, or if the device description document is invalid. Maybe you have a problem there, and that is why the other apps don't show your service... but RSSDP should still find it as it doesn't require access to the DDD endpoint in order to discover the device initially.

Using the latest version I am able to find many SSDP published devices on my home and work networks (confirmed this morning). I am also able to see my RSSDP published devices/services using both Device Sniffer and Device Spy, so I don't *think* there is an (obvious) problem with the library or with the format/content of the packets.

Perhaps see if Device Spy sees your device, if it doesn't them maybe the issue is with the DDD or the endpoint serving it.

**Comment by Reginiano** [comment] 2016-07-05 09:38
The packets are not being captured by Device Spy. :(

The sniffer finds 3 different packets::
upnp:rootdevice
pnp:rootdevice
uuid:6a3eaca028db11e6bf40800200c9a66

The upnp:rootdevice looks like this:
_NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
Date: Tue, 05 Jul 2016 09:23:33 GMT
NT: upnp:rootdevice
NTS: ssdp:alive
SERVER: Win32NT/6.1.7601.65536 Service Pack 1 UPnP/1.0 RSSDP/1.0
USN: uuid:6a3eaca028db11e6bdf40800200c9a66:upnp:rootdevice
LOCATION: http://iis-1/Device.xml
CACHE-CONTROL: public, max-age=1800_

For the test i used [this ](https://msdn.microsoft.com/en-us/library/ms885474.aspx)description xml.

**Comment by Yortw** [comment] 2016-07-05 10:29
It sounds like maybe there is a problem with accessing the DDD. Since the sniffer sees the packets it would appear the broadcast is working, but Device Spy won't show devices unless it can access and parse the DDD properly. From the remote machine can you browse to http://iis-1/Device.xml and see the valid xml? I can't recall 100%, but I think it might also require the DDD to actually match the data in the packet, and I'm not sure it does in this instance. For example the USN in the broadcast packet has values that I don't see anywhere in the link you provided for the DDD xml.

Of course that still doesn't explain why the RSSDP locator doesn't find the device, since it only needs to receive the broadcast packets to notify you of the device existence. I don't really understand that.

**Comment by Reginiano** [comment] 2016-07-05 16:16
Yortw, thank you for your availability and detailed responses. :+1: 

I matched the description xml to the packet and managed to find the device by Device Spy and [Upnp Inspector](http://coherence.beebits.net/wiki/UPnP-Inspector)!
However it still wasn't found by [Upnp Scanner](http://alax.info/blog/257).

I guess every scanner is sensitive to different fields.
The packets that are being captured by Upnp Scanner containing the following data (in addition to the RSSDP data):
_01-NLS:  d48c200427ab7b6f51fe42b1b67dbe8d
ST:  urn:microsoft-com:device:LnvConnectDevice:1
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01_
Is this data created only by the full UPnP device architecture and not available in RSSDP?

**Comment by Yortw** [comment] 2016-07-06 09:44
No problem, sorry I haven't been much help. It's hard diagnosing this stuff remotely.

Any chance you could post your publish/locate code?
Also, could you try the test console app in the RSSDP repo? You can run separate copies on separate machines, one as publisher and one as locator, and see if work together. It doesn't actually have a service so Device Spy won't see the publisher, but the app itself should find stuff published by other instances.

As for the headers above, I'm pretty sure I recall ST, that should be exposed by RSSDP somewhere I think. The others I don't recall, they may be custom headers or at least not supported by RSSDP directly. However the SsdpDevice class has a CustomHttpHeaders property. When publishing a device entries in this collection should be included in the packets. When locating a device, the device instance passed to the events or stored in the results collection should have any unrecognised headers included so your code can use them without having to request the full document (assuming the headers are in the packets).

**Comment by Reginiano** [comment] 2016-07-06 11:52
Actually you've been helpful! The important thing for me was to publish correctly, not to discover, so there's no need for me to further investigate.

However, did you wanted me to send the code and do the tests for the RSSDP benefit?
If so, no problem, i'll do it.

**Comment by Yortw** [comment] 2016-07-06 12:06
Glad I helped. Would love to know what the issue is in case anybody else comes across it, so if you can that would be great, but just in your own time. No rush. Thanks ☺

**Comment by Reginiano** [comment] 2016-07-06 14:07
Well, this might give us a lead...
For the test I used 4 different projects.

Publishing console app.
Publishing windows service.
Both publishers are successfully sending packets (found by sniffer and spy).

Discovery console app.
Discovery windows service.
Both discovery apps are finding only the console app upnp.
:question:

**Comment by Yortw** [comment] 2016-07-06 20:39
Thanks. That seems weird. I sort of suspect the service is publishing something that may or may not be invalid, but isn't being parsed/understood by the locators. Hard to know without being able to debug myself.

**Comment by Reginiano** [comment] 2016-07-06 22:55
The service app is using the same code as the console app, so maybe you can try it yourself...

**Comment by Yortw** [comment] 2016-07-21 06:17
Tried a simple Windows Service project myself and it works for me. I believe your original issue is solved anyway, so shall we close this issue, or are you still having a problem you need assistance with?

**Closed** 2016-07-31 11:28 UTC

**Comment by Reginiano** [comment] 2016-07-31 11:30
Thank you!
